Feature/register
Medical-Health-Makeit-Project/Frontend pull request #51
Opened 2023-04-06 18:13 UTC by Salvarez0212

Added inputs for blood type, gender, and country that will be display in the profile page

![image](https://user-images.githubusercontent.com/102271918/230461235-a4b1c1e1-582f-4a8c-8859-0aa013ad4948.png)

2023-04-06 21:35 UTC, ht1204 commented on src/pages/register/components/SelecBlood.register.jsx
> +      <option value="AB-"></option>
This option item should be:
```html
<option value="AB-">AB-</option>
```

2023-04-06 21:35 UTC, ht1204 commented on src/pages/register/components/SelectCountry.register.jsx
> +export const SelecCountry = ({ handleChange }) => {
This should be named:
```js
export const SelectCountry = ({ handleChange }) => {
```

2023-04-06 21:37 UTC, ht1204 commented on src/pages/register/components/SelectCountry.register.jsx
> +      <option value="Macedonia, the Former Yugoslav Republic of">
Currently the suggested name is Northern Macedonia.

2023-04-06 21:38 UTC, ht1204 commented on src/pages/register/components/SelectCountry.register.jsx
> +    </select>
I consider this list of countries should come from an object or an array and create a dynamic rendering with a loop, I suggest work on this enhancement.

2023-04-06 21:40 UTC, ht1204 commented on src/pages/register/components/SelecBlood.register.jsx
> +      <option value="AB-"></option>
I suggest an enhancement as I mention in list of countries, create an object or array an create a dynamic rendering with a loop, should be better an easier to mantain.

2023-04-06 21:40 UTC, ht1204 commented on src/pages/register/Register.page.jsx
> +            <label htmlFor="country">Selec your country:</label>
Watch this:
```html
<label htmlFor="country">Select your country:</label>
```

2023-04-06 21:40 UTC, ht1204 commented on src/pages/register/Register.page.jsx
> +  console.log(data);
What is this console.log doing here?

2023-04-06 21:41 UTC, ht1204 requested changes
Consider and address according to the comments, please and thanks in advance.

2023-04-07 05:32 UTC, Salvarez0212 commented
I have completed all the suggestions you asked for, I stay tuned if another correction is needed!

2023-04-08 05:40 UTC, JeanVittory submitted a review, later dismissed

2023-04-15 22:51 UTC, ht1204 approved these changes

2023-04-15 22:52 UTC, merged