Feature/administration page
Medical-Health-Makeit-Project/Frontend pull request #52
Opened 2023-04-07 00:28 UTC by JeanVittory

Was builded whole the router of the admin dashboard using react router dom. The next step will be start the crud of products and doctors

2023-04-07 00:45 UTC, ht1204 commented on src/components/navigationLink/NavigationLink.components.jsx
> +      ? '/home/admin/dashboard'
This route could be better in a constant variable, please make that change, about the rest, great job.

2023-04-07 00:46 UTC, ht1204 approved these changes
Please, consider the comment that I left, approve with changes to be done before merge.

2023-04-07 19:52 UTC, ht1204 approved these changes

2023-04-07 22:28 UTC, ht1204 requested changes
This is Still WIP, this could be a draft PR yet, attentive to updates

2023-04-08 05:36 UTC, JeanVittory commented on src/components/navigationLink/NavigationLink.components.jsx
> +      ? '/home/admin/dashboard'
This recommendation was resolved in commit number c762457

2023-04-08 20:25 UTC, ht1204 approved these changes

2023-04-08 20:26 UTC, merged