Feature/profiles
Medical-Health-Makeit-Project/Frontend pull request #55
Opened 2023-04-10 04:57 UTC by Salvarez0212

The functionality of updating the email and phone number for both the role of patient and the doctor was added

Before update:
![image](https://user-images.githubusercontent.com/102271918/230828762-8b77a8d7-9516-47ea-ac6d-53339e890fbf.png)

Updating:
![image](https://user-images.githubusercontent.com/102271918/230828916-6a1d465a-bdd3-4b74-8923-02d39072fd52.png)

After update:
![image](https://user-images.githubusercontent.com/102271918/230828999-c9fd2480-4835-468c-a6a1-8da3cfadada2.png)

2023-04-10 15:13 UTC, ht1204 requested changes
Please, address each comment for a better job, keep pushing forward, attentive to any updates.

2023-04-10 15:13 UTC, ht1204 commented on src/pages/profiles/components/doctorProfile/DoctorProfile.page.jsx
> +                  pattern="/^\s*(?:\+?(\d{1,3}))?[-. (]*(\d{3})[-. )]*(\d{3})[-. ]*(\d{4})(?: *x(\d+))?\s*$/"
This regex pattern could be better in a constant to assign to this input-prop.

2023-04-10 15:13 UTC, ht1204 commented on src/pages/profiles/components/doctorProfile/doctorProfile.page.scss
> +  display: none !important;
using `!important` is not a great idea, is there a better styling choice?

2023-04-10 15:13 UTC, ht1204 commented on src/pages/profiles/components/doctorProfile/doctorProfile.page.scss
> +  border-bottom: solid 1px #2762c182;
Hexadecimal color should have six (6) digits, I think there is an issue here.
I also recommend to respect the syntaxis: `border-bottom: 1px solid #HEXCOLOR`.

2023-04-10 15:13 UTC, ht1204 commented on src/pages/profiles/components/userProfile/UserProfile.page.jsx
> +    //axios
`//@TO-DO: assign link to backend for updating actions`.
The comments must be clear for a better understanding.

2023-04-10 15:13 UTC, ht1204 commented on src/pages/profiles/components/userProfile/UserProfile.page.jsx
> +              pattern="^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}"
this regex pattern could be better in a constant.

2023-04-10 15:13 UTC, ht1204 commented on src/pages/profiles/components/userProfile/UserProfile.page.jsx
> +              pattern="/^\s*(?:\+?(\d{1,3}))?[-. (]*(\d{3})[-. )]*(\d{3})[-. ]*(\d{4})(?: *x(\d+))?\s*$/"
also here.

2023-04-10 15:13 UTC, ht1204 commented on src/pages/profiles/components/userProfile/userProfile.page.scss
> +  display: none !important;
is there a better option instead of using `!important`?

2023-04-10 15:13 UTC, ht1204 commented on src/pages/profiles/components/userProfile/userProfile.page.scss
> +  border-bottom: solid 1px #2762c182;
same comment as border-bottom above.

2023-04-10 15:13 UTC, ht1204 commented on src/pages/register/Register.page.jsx
> +            <label htmlFor="blood_type">Selec your blood type:</label>
`Select your blood type:`
Every detail is important.

2023-04-10 15:13 UTC, ht1204 commented on src/pages/register/Register.page.jsx
> +              name="gneder"
`name="gender"`

2023-04-10 15:13 UTC, ht1204 commented on src/pages/register/components/SelectCountry.register.jsx
> +    'Macedonia',
`Northern Macedonia`

2023-04-12 17:11 UTC, Salvarez0212 commented on src/pages/register/components/SelectCountry.register.jsx
> +    'Macedonia',
All typos in register page fixed in feature/register branch in it´s respective PR

2023-04-15 22:48 UTC, ht1204 approved these changes
Approve to move forward, DO NOT forget the comments for changes and fixes.

2023-04-15 22:49 UTC, merged